# If not running interactively, don't do anything
[ -z "$PS1" ] && return


brew_prefix=""
if which brew &> /dev/null; then
	brew_prefix=$(brew --prefix)
fi

source ~/dotfiles/private/platform

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
for file in ~/dotfiles/shells/bash.d/{history,aliases,functions,exports}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# use this for commands and things that should only be local
if [ -e ~/.bash_local ]; then
	source ~/.bash_local
fi

if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*


