---
- hosts: all
  vars:
    applications:
      - 1password
      - bitbar
      - disk-inventory-x
      - firefox
      - flux
      - google-chrome
      - keybase
      - oversight
      - robo3T
      - rocket
      - skype
      - slack
      - spotify
      - sublime-text3
      - vagrant
      - vagrant-manager
      - vanilla
      - virtualbox
      - vlc
    brew_taps:
      - caskroom/cask
      - caskroom/versions # for sublime-text3
      - homebrew/binary
      - homebrew/dupes
      - homebrew/versions
    dotfile_repo_username: criva
    brew_utils:
      - autojump
      - bash
      - bash-completion2
      - brew-cask
      - findutils
      - git
      - moreutils
      - nmap
      - pycodestyle
      - ssh-copy-id
      - thefuck
    home: "{{ lookup('env', 'HOME' }}"
  tasks:
    - name: HOMEBREW | Install required Taps
      shell: brew tap {{ item }}
      with_items: brew_taps

    - name: HOMEBREW | Install Cask
      shell: brew install brew-cask

    - name: UTILS | Install
      homebrew:
        name: "{{ item }}"
        state: present
      with_items: brew_utils

    - name: UTILS | Cleanup
      shell: brew cleanup

    - name: CASKS | load list
      shell: brew cask list | grep {{ item }}
      register: installed_applications
      with_items: applications
      ignore_errors: true

    - name: CASKS | install
      shell: brew cask install {{ item }}
      with_items: applications
      when: "{{ item not in installed_applications.results|map(attribute='stdout') }}"
